server.port=8089
spring.application.name=recomendaciones-service

spring.datasource.url=jdbc:mariadb://localhost:3310/db_recomendaciones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true