# Nombre del microservicio y puerto
spring.application.name=partidos-service
server.port=8082

# Configuración de la Base de Datos (MySQL en XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/db_partidos?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate (crea las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update

# Conexión al servidor Eureka (Monorepo)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

